import { SvgProps } from "react-native-svg";
export declare type IconType = (props: SvgProps & { fill?: string }) => React.FunctionComponent;
export declare const ArrowUpIcon: IconType;
export declare const BookmarkOutlineIcon: IconType;
export declare const BookmarkIcon: IconType;
export declare const BoxIcon: IconType;
export declare const ChevronLeftIcon: IconType;
export declare const CreateARIcon: IconType;
export declare const ErrorOutlineIcon: IconType;
export declare const ExploreIcon: IconType;
export declare const ForwardIcon: IconType;
export declare const GPSIcon: IconType;
export declare const HomeIcon: IconType;
export declare const LocateIcon: IconType;
export declare const LocationIcon: IconType;
export declare const MenuIcon: IconType;
export declare const PauseDarkIcon: IconType;
export declare const PlayDarkIcon: IconType;
export declare const ProfileIcon: IconType;
export declare const ReplayIcon: IconType;
export declare const SearchIcon: IconType;
export declare const ShareIcon: IconType;
export declare const SortIcon: IconType;
export declare const TimeIcon: IconType;
